Update for python math.js
RichDoherty/blockly pull request #3
Opened 2021-11-05 01:45 UTC by LouisCatala

## The basics

- [ ] I branched from develop
- [ ] My pull request is against develop
- [ ] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

## The details
### Resolves

### Proposed Changes

#### Behavior Before Change

#### Behavior After Change

### Reason for Changes

### Test Coverage

### Documentation

### Additional Information

2021-11-05 05:07 UTC, RichDoherty requested changes

2021-11-05 05:07 UTC, RichDoherty commented on generators/python/math.js
> +    if (!divisor || divisor == '0') {
Change `==` to `===`.

2021-11-05 05:07 UTC, RichDoherty commented on generators/python/math.js
> +    Blockly.Python.ORDER_MULTIPLICATIVE) || '0';
Blockly.Python.ORDER_MULTIPLICATIVE) || '0'; needs to be indented.

2021-11-05 05:07 UTC, RichDoherty commented on generators/python/math.js
> +  if (dropdownProperty == 'PRIME') {
Change `==` to `===`.

2021-11-08 00:32 UTC, jeremyjacob123 requested changes

2021-11-08 00:32 UTC, jeremyjacob123 commented on generators/python/math.js
> +    if (!divisor || divisor === '0') {
`!divisor` is not needed, as it will always be `false`.
```suggestion
    if (divisor === '0') {
```

2021-11-08 00:47 UTC, jeremyjacob123 approved these changes

2021-11-08 00:50 UTC, RichDoherty approved these changes

2021-11-08 00:52 UTC, merged

2021-11-09 03:04 UTC, jschanker commented on generators/python/math.js
> +       code = functionName + '(' + numberToCheck + ')';
`code` should only be indented four spaces to line up with `const functionName` above.

2021-11-09 03:05 UTC, jschanker commented on generators/python/math.js
> +  }
A semicolon is required here to conform to Google's style guide.