Develop math number property operator precedence lua
RichDoherty/blockly pull request #6
Opened 2021-11-05 02:33 UTC by jeremyjacob123

## The basics

- [ ] I branched from develop
- [ ] My pull request is against develop
- [ ] My code follows the [style guide](https://developers.google.com/blockly/guides/modify/web/style-guide)

## The details
### Resolves

### Proposed Changes

#### Behavior Before Change

#### Behavior After Change

### Reason for Changes

### Test Coverage

### Documentation

### Additional Information

2021-11-06 03:26 UTC, RichDoherty commented on generators/lua/math.js
> +  if (dropdownProperty == 'PRIME') {
Change `==` to `===`

2021-11-06 03:26 UTC, RichDoherty commented on generators/lua/math.js
> +        } else if (dropdownProperty == 'DIVISIBLE_BY') {
Change `==` to `===`

2021-11-06 03:26 UTC, RichDoherty commented on generators/lua/math.js
> -      }
This is missing from the updated code.

2021-11-06 03:26 UTC, RichDoherty commented on generators/lua/math.js
> +
Remove blank lines as per the style guide. https://developers.google.com/blockly/guides/modify/web/style-guide

2021-11-06 04:06 UTC, jschanker requested changes
After fixing indentation issues and unnecessary line breaks, LGTM.

2021-11-06 04:06 UTC, jschanker commented on generators/lua/math.js
> +           if (!divisor || divisor == '0') {
By using `|| '0'` in the initialization of `divisor` above, `!divisor` becomes unnecessary here.

2021-11-06 04:37 UTC, jschanker approved these changes

2021-11-07 06:46 UTC, jschanker requested changes

2021-11-07 06:46 UTC, jschanker commented on generators/lua/math.js
> +    if (divisor == '0') {
This should now be `===` since `divisor` will be a string.

2021-11-07 23:01 UTC, merged

2021-11-09 02:52 UTC, jschanker commented on generators/lua/math.js
> +
Delete these lines from the old version. (Note that they're duplicated above except `const` is used instead of `var`.)

2021-11-09 02:52 UTC, jschanker commented on generators/lua/math.js
> +         code = functionName + '(' + numberToCheck + ')';
This line should only be indented four spaces; it should line up with `const functionName` above.